export type EnvType = {
  EXPO_PUBLIC_API_URL: string;
  EXPO_PUBLIC_HEADER_KEY_KEY: string;
  EXPO_PUBLIC_HEADER_KEY_VALUE: string;
  EXPO_PUBLIC_HEADER_HOST_KEY: string;
  EXPO_PUBLIC_HEADER_HOST_VALUE: string;
  EXPO_PUBLIC_MIXPANEL_PROJECT_KEY: string;
};
